### ISSUE TITLE
FuzzedDataProvider::ConsumeSmallIntInRange reads from the back of input, rather than the front

### ISSUE THREAD

**Issue by alex** [google/atheris#10]
https://github.com/google/atheris/blob/master/fuzzed_data_provider.cc#L256

Based on `Advance` I'd expect every method which looks at data to read from the front of the input (`data_ptr[0]`), but `ConsumeSmallIntInRange` reads from the back (`data_ptr_`).

**Comment by IanPudney** [comment]
Hi Alex,

I'm sorry, I meant to respond to this much earlier. I got this behavior from LLVM's FuzzedDataProvider:
https://github.com/llvm/llvm-project/blob/70de7e0d9a95b7fcd7c105b06bd90fdf4e01f563/compiler-rt/include/fuzzer/FuzzedDataProvider.h#L217
Apparently, it experimentally works better.

**Comment by alex** [comment]
Huh, interesting. I found it confusing when I was trying to manually craft fuzzer inputs, but if it works better than I guess that's what's important!
