### ISSUE TITLE
MAP_ANONYMOUS not available on older MacOS

### ISSUE THREAD

**Issue by bollwyvl** [google/atheris#28]
Thanks for atheris, and congrats on the 2.0.8 release (and a tag on the repo pointed to it)!

It looks like the use of [`MAP_ANONYMOUS` in `counters.cc`](https://github.com/google/atheris/blob/2.0.8/src/native/counters.cc#L112-L115) seems to raise the minimum supported OSX to 10.10. While this doesn't _strictly_ bother me, downstream on [conda-forge](https://github.com/conda-forge/atheris-feedstock/pull/2) we generally try to keep the compatibility window as wide as possible. To get something out the door, [this patch](https://github.com/conda-forge/atheris-feedstock/pull/2/files#diff-987584cd28e54cfdfecfba54469e269de9fab3ab1b40886ae3b8e7ec094c71f7) uses the _apparently_ equivalent `MAP_ANON` and passes the simple smoke test from the repo, but we only apply it on OSX.

I guess it would be good to either:
- handle these somewhat older OSX versions (not sure what it would take to support both)
- declare the minimum OSX (in which case I can bump the minimum deployment target)

Thanks again!

**Comment by bollwyvl** [comment]
Thanks!

**Comment by TheShiftedBit** [comment]
Updated. Give it a try and check if it works.

**Comment by bollwyvl** [comment]
Yes indeed, works as advertised! The quick response is much appreciated.
