### ISSUE TITLE
Please add a tag for the latest release

### ISSUE THREAD

**Issue by grawlinson** [google/atheris#45]
Hello, package maintainer for Arch Linux here.

I'm just wondering if the maintainers of this fine project would be able to add a git tag for the latest release (2.0.12)?

**Comment by TheShiftedBit** [comment]
Done.

**Comment by grawlinson** [comment]
Thank you very much! :)

**Comment by TheShiftedBit** [comment]
You're welcome. We recently improved our test and release automation, but
it seems we forgot that step.
