### ISSUE TITLE
Instrumenting time long

### ISSUE THREAD

**Issue by huan1372** [google/atheris#47]
Hi, I am currently working on collecting tensorflow library coverage with different tests by Atheris. However, each time it took long time to instrumenting the tf library.
Is there a way that I could set all test1.py, test2.py ... files to instrument same library so that I only need to run instrumentation once for all test.py files?

**Comment by TheShiftedBit** [comment]
Unfortunately, atheris doesn't provide any feature to dump out the
instrumented versions of libraries and save them for later.

You might be able to make something to speed up development with os.fork():
after instrumentation but before starting fuzzing, fork the program several
times and run a different fuzz function in each child. You could even have
your program wait for stdin, and then fork, load a module, and fuzz a
function in it.

That's just a guess though. It might not work. And it definitely won't if
any of the modules start threads before the fork.

**Comment by huan1372** [comment]
Thanks for your quick response! Let me have a try!

**Comment by babenek** [comment]
@huan1372 ,
If you collect seeds files and want to collect coverage only, you can run only tests without instrumenting.
It helps to check common functionality quickly.
Do fuzzing again (with instrumenting and additional -atheris_runs) in important cases.
e.g. https://github.com/Samsung/CredSweeper/blob/main/fuzz/coveraging.sh
